version: "3"
services:
    web-api:
        image: programa-fidelidade-dotz:latest
        container_name: programa-fidelidade-dotz-api 
        build:
            context: ../src
            dockerfile: ./WebApi/Dockerfile
        ports:
            - 5001:5001
        environment:      
            - ASPNETCORE_URLS=http://*:5001
    db:
        image: mysql:8.0
        container_name: mysql8
        restart: always
        ports: 
            - 3306:3306
        environment:             
            MYSQL_ROOT_PASSWORD: "!DbProgramaFidelidade2021"
        cap_add: 
            - SYS_NICE
    adminer:
        image: adminer:4
        container_name: adminer_container
        restart: always
        ports: 
            - 8080:8080
            